const Sequelize = require('sequelize');
module.exports = function (sequelize, DataTypes) {
    return sequelize.define('FIN_Purchases', {
    PurID: {type: DataTypes.INTEGER,allowNull: false,autoIncrement: true,primaryKey: true},
    PurDesc: {type: DataTypes.STRING(4000),allowNull: true},
    VendID: {type: DataTypes.INTEGER,allowNull: false},
    VendCode: {type: DataTypes.STRING(255),allowNull: false},
    VendDesc: {type: DataTypes.STRING(255),allowNull: false},
    TransDate: {type: DataTypes.DATEONLY,allowNull: false},
    TransNo: {type: DataTypes.STRING(255),allowNull: true},
    PayTermID: {type: DataTypes.INTEGER,allowNull: false},
    PayTermCode: {type: DataTypes.STRING(255),allowNull: false},
    PayTermDesc: {type: DataTypes.STRING(255),allowNull: false},
    LocationID: {type: DataTypes.INTEGER,allowNull: false},
    LocationCode: {type: DataTypes.STRING(255),allowNull: false},
    Location: {type: DataTypes.STRING(255),allowNull: false},
    TransType: {type: DataTypes.STRING(255),allowNull: true},
    CurID: {type: DataTypes.INTEGER,allowNull: false},
    CurCode: {type: DataTypes.STRING(255),allowNull: false},
    CurDesc: {type: DataTypes.STRING(255),allowNull: false},
    JobID: {type: DataTypes.INTEGER,allowNull: false},
    JobCode: {type: DataTypes.STRING(255),allowNull: false},
    JobDesc: {type: DataTypes.STRING(255),allowNull: false},
    ExchRate: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    SubTotal: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    PurAmount: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    PurAmountCur: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    SubTotalCur: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    TotalAmountCur: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    TaxAmountCur: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    TaxCode: {type: DataTypes.STRING(255),allowNull: true},
    TaxDesc: {type: DataTypes.STRING(255),allowNull: true},
    TaxAmount: {type: DataTypes.STRING(255),allowNull: false},
    TotalAmount: {type: DataTypes.STRING(255),allowNull: false},
    RemitToAdrID : {type: DataTypes.INTEGER,allowNull: true},
    RemitToAdrCode: {type: DataTypes.STRING(255),allowNull: true},
    RemitToAdrDesc: {type: DataTypes.STRING(255),allowNull: true},
    ShipFrAdrID : {type: DataTypes.INTEGER,allowNull: true},
    ShipFrAdrCode: {type: DataTypes.STRING(255),allowNull: true},
    ShipFrAdrDesc: {type: DataTypes.STRING(255),allowNull: true},
    Discount: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    SpDiscount: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    Freight: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    DiscountCur: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    FreightCur: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    PrdID: {type: DataTypes.INTEGER,allowNull: true},
    DiscAmount: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    AplAmount: {type: DataTypes.DECIMAL(18,5),allowNull: true},
    Closed: {type: DataTypes.BOOLEAN,allowNull: true},
    JrnlID: {type: DataTypes.INTEGER,allowNull: true},
    LayoutID: {type: DataTypes.INTEGER,allowNull: true},
    CreatedUser: {type: DataTypes.STRING,allowNull: true},
    Status: {type: DataTypes.INTEGER,allowNull: true},
    BranchCode: {type: DataTypes.STRING(255),allowNull: true},
    Period: {type: DataTypes.STRING(255),allowNull: true},
    YearID: {type: DataTypes.INTEGER,allowNull: true},
    ModifyUser: {type: DataTypes.STRING(255),allowNull: true},
    PostedUser: {type: DataTypes.STRING(255),allowNull: true},
    postedAt: {type: DataTypes.DATE,allowNull: true},
    VenRefNo: {type: DataTypes.STRING(255),allowNull: true},
    }, {
        sequelize,
        tableName: 'FIN_Purchases',
    schema: 'dbo',
    timestamps: true,
    });
};
